"use strict";var userAgent=navigator.userAgent.toLowerCase(),initialDate=new Date(),$document=$(document),$window=$(window),$html=$("html"),isDesktop=$html.hasClass("desktop"),isNoviBuilder=window.xMode,isIE=userAgent.indexOf("msie")!=-1?parseInt(userAgent.split("msie")[1]):userAgent.indexOf("trident")!=-1?11:userAgent.indexOf("edge")!=-1?12:false,isMobile=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),isTouch="ontouchstart"in window,plugins={pointerEvents:isIE<11?"js/pointer-events.min.js":false,bootstrapTooltip:$("[data-toggle='tooltip']"),bootstrapModalDialog:$('.modal'),bootstrapTabs:$(".tabs-custom"),rdNavbar:$(".rd-navbar"),rdParallax:$(".rd-parallax"),rdGoogleMaps:$(".rd-google-map"),rdMailForm:$(".rd-mailform"),rdInputLabel:$(".form-label"),regula:$("[data-constraints]"),owl:$(".owl-carousel"),swiper:$(".swiper-slider"),search:$(".rd-search"),searchResults:$('.rd-search-results'),mfp:$('[data-lightbox]').not('[data-lightbox="gallery"] [data-lightbox]'),mfpGallery:$('[data-lightbox^="gallery"]'),statefulButton:$('.btn-stateful'),isotope:$(".isotope"),popover:$('[data-toggle="popover"]'),viewAnimate:$('.view-animate'),photoSwipeGallery:$("[data-photo-swipe-item]"),radio:$("input[type='radio']"),checkbox:$("input[type='checkbox']"),customToggle:$("[data-custom-toggle]"),counter:$(".counter"),progressLinear:$(".progress-linear"),circleProgress:$(".progress-bar-circle"),dateCountdown:$('.DateCountdown'),pageLoader:$("#page-loader"),flickrfeed:$(".flickr"),selectFilter:$("select"),rdAudioPlayer:$(".rd-audio"),rdVideoBG:$(".rd-video"),mojsIconEffect:$('.mojs-icon-effect'),customParallax:$(".custom-parallax"),slick:$('.slick-slider')};$document.ready(function(){function getSwiperHeight(object,attr){var val=object.attr("data-"+attr),dim;if(!val){return undefined;}
dim=val.match(/(px)|(%)|(vh)$/i);if(dim.length){switch(dim[0]){case "px":return parseFloat(val);case "vh":return $(window).height()*(parseFloat(val)/100);case "%":return object.width()*(parseFloat(val)/100);}}else{return undefined;}}
function toggleSwiperInnerVideos(swiper){var prevSlide=$(swiper.slides[swiper.previousIndex]),nextSlide=$(swiper.slides[swiper.activeIndex]),videos;prevSlide.find("video").each(function(){this.pause();});videos=nextSlide.find("video");if(videos.length){videos.get(0).play();}}
function toggleSwiperCaptionAnimation(swiper){var prevSlide=$(swiper.container),nextSlide=$(swiper.slides[swiper.activeIndex]);prevSlide.find("[data-caption-animate]").each(function(){var $this=$(this);$this.removeClass("animated").removeClass($this.attr("data-caption-animate")).addClass("not-animated");});nextSlide.find("[data-caption-animate]").each(function(){var $this=$(this),delay=$this.attr("data-caption-delay");if(!isNoviBuilder){setTimeout(function(){$this.removeClass("not-animated").addClass($this.attr("data-caption-animate")).addClass("animated");},delay?parseInt(delay):0);}else{$this.removeClass("not-animated")}});}
function makeParallax(el,speed,wrapper,prevScroll){var scrollY=window.scrollY||window.pageYOffset;if(prevScroll!=scrollY){prevScroll=scrollY;el.addClass('no-transition');el[0].style['transform']='translate3d(0,'+-scrollY*(1-speed)+'px,0)';el.height();el.removeClass('no-transition');if(el.attr('data-fade')==='true'){var bound=el[0].getBoundingClientRect(),offsetTop=bound.top*2+scrollY,sceneHeight=wrapper.outerHeight(),sceneDevider=wrapper.offset().top+sceneHeight/2.0,layerDevider=offsetTop+el.outerHeight()/2.0,pos=sceneHeight/6.0,opacity;console.log(sceneDevider+pos+', '+layerDevider+','+pos);if(sceneDevider+pos>layerDevider&&sceneDevider-pos<layerDevider){el[0].style["opacity"]=1;}else{if(sceneDevider-pos<layerDevider){opacity=1+((sceneDevider+pos-layerDevider)/sceneHeight/3.0*5);}else{opacity=1-((sceneDevider-pos-layerDevider)/sceneHeight/3.0*5);}
el[0].style["opacity"]=opacity<0?0:opacity>1?1:opacity.toFixed(2);}}}
requestAnimationFrame(function(){makeParallax(el,speed,wrapper,prevScroll);});}
function initOwlCarousel(c){var aliaces=["-","-xs-","-sm-","-md-","-lg-","-xl-"],values=[0,480,768,992,1200,1600],responsive={},j,k;for(j=0;j<values.length;j++){responsive[values[j]]={};for(k=j;k>=-1;k--){if(!responsive[values[j]]["items"]&&c.attr("data"+aliaces[k]+"items")){responsive[values[j]]["items"]=k<0?1:parseInt(c.attr("data"+aliaces[k]+"items"));}
if(!responsive[values[j]]["stagePadding"]&&responsive[values[j]]["stagePadding"]!==0&&c.attr("data"+aliaces[k]+"stage-padding")){responsive[values[j]]["stagePadding"]=k<0?0:parseInt(c.attr("data"+aliaces[k]+"stage-padding"));}
if(!responsive[values[j]]["margin"]&&responsive[values[j]]["margin"]!==0&&c.attr("data"+aliaces[k]+"margin")){responsive[values[j]]["margin"]=k<0?30:parseInt(c.attr("data"+aliaces[k]+"margin"));}}}
if(c.attr('data-dots-custom')){c.on("initialized.owl.carousel",function(event){var carousel=$(event.currentTarget),customPag=$(carousel.attr("data-dots-custom")),active=0;if(carousel.attr('data-active')){active=parseInt(carousel.attr('data-active'));}
carousel.trigger('to.owl.carousel',[active,300,true]);customPag.find("[data-owl-item='"+active+"']").addClass("active");customPag.find("[data-owl-item]").on('click',function(e){e.preventDefault();carousel.trigger('to.owl.carousel',[parseInt(this.getAttribute("data-owl-item")),300,true]);});carousel.on("translate.owl.carousel",function(event){customPag.find(".active").removeClass("active");customPag.find("[data-owl-item='"+event.item.index+"']").addClass("active")});});}
if(typeof(c.attr("data-numbering"))!=='undefined'){var numberingObject=$(c.attr("data-numbering"));c.on('initialized.owl.carousel changed.owl.carousel',function(numberingObject){return function(e){if(!e.namespace)return;numberingObject.find('.numbering-current').text((e.item.index+1)%e.item.count+1);numberingObject.find('.numbering-count').text(e.item.count);};}(numberingObject));}
c.owlCarousel({autoplay:c.attr("data-autoplay")==="true",loop:isNoviBuilder==="designMode"?false:c.attr("data-loop")!=="false",items:1,dotsContainer:c.attr("data-pagination-class")||false,navContainer:c.attr("data-navigation-class")||false,mouseDrag:isNoviBuilder==="designMode"?false:c.attr("data-mouse-drag")!=="false",nav:c.attr("data-nav")==="true",dots:c.attr("data-dots")==="true",dotsEach:c.attr("data-dots-each")?parseInt(c.attr("data-dots-each")):false,animateIn:c.attr('data-animation-in')?c.attr('data-animation-in'):'slide',animateOut:c.attr('data-animation-out')?c.attr('data-animation-out'):false,responsive:responsive,navText:$.parseJSON(c.attr("data-nav-text"))||[],navClass:$.parseJSON(c.attr("data-nav-class"))||['owl-prev','owl-next']});}
function moJsIconsEffect(el,options){this.el=el;this.options=$.extend({},this.options);$.extend(this.options,options);this.checked=false;this.hovered=false;this.timeline=new mojs.Timeline();for(var i=0,len=this.options.tweens.length;i<len;++i){this.timeline.add(this.options.tweens[i]);}
var self=this;this.el.addEventListener('mouseenter',function(e){if(self.hovered==false){self.options.onCheck(self.el);self.timeline.replay();self.hovered=true;self.checked=!self.checked;}});this.el.addEventListener('mouseleave',function(e){if(self.hovered){self.options.onUnCheck(self.el);self.checked=!self.checked;self.hovered=false;}});}
moJsIconsEffect.prototype.options={tweens:[new mojs.Burst({})],onCheck:function(){return false;},onUnCheck:function(){return false;}};function isScrolledIntoView(elem){var $window=$(window);return elem.offset().top+elem.outerHeight()>=$window.scrollTop()&&elem.offset().top<=$window.scrollTop()+$window.height();}
function lazyInit(element,func){var $win=jQuery(window);$win.on('load scroll',function(){if((!element.hasClass('lazy-loaded')&&(isScrolledIntoView(element)))){func.call();element.addClass('lazy-loaded');}});}
if(plugins.pageLoader.length>0){$window.on("load",function(){var loader=setTimeout(function(){plugins.pageLoader.addClass("loaded");$window.trigger("resize");},100);});}
if(plugins.owl.length){var i;for(i=0;i<plugins.owl.length;i++){initOwlCarousel($(plugins.owl[i]));}}
function liveSearch(options){$('#'+options.live).removeClass('cleared').html();options.current++;options.spin.addClass('loading');$.get(handler,{s:decodeURI(options.term),liveSearch:options.live,dataType:"html",liveCount:options.liveCount,filter:options.filter,template:options.template},function(data){options.processed++;var live=$('#'+options.live);if(options.processed==options.current&&!live.hasClass('cleared')){live.find('> #search-results').removeClass('active');live.html(data);setTimeout(function(){live.find('> #search-results').addClass('active');},50);}
options.spin.parents('.rd-search').find('.input-group-addon').removeClass('loading');})}
function attachFormValidator(elements){for(var i=0;i<elements.length;i++){var o=$(elements[i]),v;o.addClass("form-control-has-validation").after("<span class='form-validation'></span>");v=o.parent().find(".form-validation");if(v.is(":last-child")){o.addClass("form-control-last-child");}}
elements.on('input change propertychange blur',function(e){var $this=$(this),results;if(e.type!="blur"){if(!$this.parent().hasClass("has-error")){return;}}
if($this.parents('.rd-mailform').hasClass('success')){return;}
if((results=$this.regula('validate')).length){for(i=0;i<results.length;i++){$this.siblings(".form-validation").text(results[i].message).parent().addClass("has-error")}}else{$this.siblings(".form-validation").text("").parent().removeClass("has-error")}}).regula('bind');}
function isValidated(elements){var results,errors=0;if(elements.length){for(j=0;j<elements.length;j++){var $input=$(elements[j]);if((results=$input.regula('validate')).length){for(k=0;k<results.length;k++){errors++;$input.siblings(".form-validation").text(results[k].message).parent().addClass("has-error");}}else{$input.siblings(".form-validation").text("").parent().removeClass("has-error")}}
return errors==0;}
return true;}
function initBootstrapTooltip(tooltipPlacement){if(window.innerWidth<599){plugins.bootstrapTooltip.tooltip('destroy');plugins.bootstrapTooltip.tooltip({placement:'bottom'});}else{plugins.bootstrapTooltip.tooltip('destroy');plugins.bootstrapTooltip.tooltipPlacement;plugins.bootstrapTooltip.tooltip();}}
var o=$("#copyright-year");if(o.length){o.text(initialDate.getFullYear());}
if(navigator.platform.match(/(Mac)/i))$html.addClass("mac-os");if(isIE){if(isIE<10){$html.addClass("lt-ie-10");}
if(isIE<11){if(plugins.pointerEvents){$.getScript(plugins.pointerEvents).done(function(){$html.addClass("ie-10");PointerEventsPolyfill.initialize({});});}}
if(isIE===11){$("html").addClass("ie-11");}
if(isIE===12){$("html").addClass("ie-edge");}}
if(plugins.bootstrapTooltip.length){var tooltipPlacement=plugins.bootstrapTooltip.attr('data-placement');initBootstrapTooltip(tooltipPlacement);$(window).on('resize orientationchange',function(){initBootstrapTooltip(tooltipPlacement);})}
if(plugins.bootstrapModalDialog.length>0){var i=0;for(i=0;i<plugins.bootstrapModalDialog.length;i++){var modalItem=$(plugins.bootstrapModalDialog[i]);modalItem.on('hidden.bs.modal',$.proxy(function(){var activeModal=$(this),rdVideoInside=activeModal.find('video'),youTubeVideoInside=activeModal.find('iframe');if(rdVideoInside.length){rdVideoInside[0].pause();}
if(youTubeVideoInside.length){var videoUrl=youTubeVideoInside.attr('src');youTubeVideoInside.attr('src','').attr('src',videoUrl);}},modalItem))}}
if(plugins.rdGoogleMaps.length){var i;$.getScript("//maps.google.com/maps/api/js?key=AIzaSyAwH60q5rWrS8bXwpkZwZwhw9Bw0pqKTZM&sensor=false&libraries=geometry,places&v=3.7",function(){var head=document.getElementsByTagName('head')[0],insertBefore=head.insertBefore;head.insertBefore=function(newElement,referenceElement){if(newElement.href&&newElement.href.indexOf('//fonts.googleapis.com/css?family=Roboto')!=-1||newElement.innerHTML.indexOf('gm-style')!=-1){return;}
insertBefore.call(head,newElement,referenceElement);};for(i=0;i<plugins.rdGoogleMaps.length;i++){var $googleMapItem=$(plugins.rdGoogleMaps[i]);lazyInit($googleMapItem,$.proxy(function(){var $this=$(this),styles=$this.attr("data-styles");$this.googleMap({styles:styles?JSON.parse(styles):[],onInit:function(map){var inputAddress=$('#rd-google-map-address');if(inputAddress.length){var input=inputAddress;var geocoder=new google.maps.Geocoder();var marker=new google.maps.Marker({map:map,icon:"images/gmap_marker.png",});var autocomplete=new google.maps.places.Autocomplete(inputAddress[0]);autocomplete.bindTo('bounds',map);inputAddress.attr('placeholder','');inputAddress.on('change',function(){$("#rd-google-map-address-submit").trigger('click');});inputAddress.on('keydown',function(e){if(e.keyCode==13){$("#rd-google-map-address-submit").trigger('click');}});$("#rd-google-map-address-submit").on('click',function(e){e.preventDefault();var address=input.val();geocoder.geocode({'address':address},function(results,status){if(status==google.maps.GeocoderStatus.OK){var latitude=results[0].geometry.location.lat();var longitude=results[0].geometry.location.lng();map.setCenter(new google.maps.LatLng(parseFloat(latitude),parseFloat(longitude)));marker.setPosition(new google.maps.LatLng(parseFloat(latitude),parseFloat(longitude)))}});});}}});},$googleMapItem));}});}
if(plugins.radio.length){var i;for(i=0;i<plugins.radio.length;i++){var $this=$(plugins.radio[i]);$this.addClass("radio-custom").after("<span class='radio-custom-dummy'></span>")}}
if(plugins.checkbox.length){var i;for(i=0;i<plugins.checkbox.length;i++){var $this=$(plugins.checkbox[i]);$this.addClass("checkbox-custom").after("<span class='checkbox-custom-dummy'></span>")}}
if(plugins.popover.length){if(window.innerWidth<767){plugins.popover.attr('data-placement','bottom');plugins.popover.popover();}
else{plugins.popover.popover();}}
if(plugins.statefulButton.length){$(plugins.statefulButton).on('click',function(){var statefulButtonLoading=$(this).button('loading');setTimeout(function(){statefulButtonLoading.button('reset')},2000);})}
if(isDesktop&&!isNoviBuilder){$().UItoTop({easingType:'easeOutQuart',containerClass:'ui-to-top fa fa-angle-up'});}
if(plugins.rdNavbar.length){plugins.rdNavbar.RDNavbar({stickUpClone:isNoviBuilder!=="designMode"?plugins.rdNavbar.attr('data-stick-up-clone')=='true':false,responsive:{0:{stickUp:plugins.rdNavbar.attr("data-stick-up")?(!isNoviBuilder?plugins.rdNavbar.attr("data-stick-up")==='true':false):isNoviBuilder!=="designMode"},768:{stickUp:plugins.rdNavbar.attr("data-sm-stick-up")?(!isNoviBuilder?plugins.rdNavbar.attr("data-sm-stick-up")==='true':false):isNoviBuilder!=="designMode"},992:{stickUp:plugins.rdNavbar.attr("data-md-stick-up")?(!isNoviBuilder?plugins.rdNavbar.attr("data-md-stick-up")==='true':false):isNoviBuilder!=="designMode"},1200:{stickUp:plugins.rdNavbar.attr("data-lg-stick-up")?(!isNoviBuilder?plugins.rdNavbar.attr("data-lg-stick-up")==='true':false):isNoviBuilder!=="designMode"}}});if(plugins.rdNavbar.attr("data-body-class")){document.body.className+=' '+plugins.rdNavbar.attr("data-body-class");}}
if(plugins.viewAnimate.length){var i;for(i=0;i<plugins.viewAnimate.length;i++){var $view=$(plugins.viewAnimate[i]).not('.active');$document.on("scroll",$.proxy(function(){if(isScrolledIntoView(this)){this.addClass("active");}},$view)).trigger("scroll");}}
if(plugins.swiper.length){var i;for(i=0;i<plugins.swiper.length;i++){var s=$(plugins.swiper[i]);var pag=s.find(".swiper-pagination"),next=s.find(".swiper-button-next"),prev=s.find(".swiper-button-prev"),bar=s.find(".swiper-scrollbar"),parallax=s.parents('.rd-parallax').length,swiperSlide=s.find(".swiper-slide"),autoplay=false;for(j=0;j<swiperSlide.length;j++){var $this=$(swiperSlide[j]),url;if(url=$this.attr("data-slide-bg")){$this.css({"background-image":"url("+url+")","background-size":"cover"})}}
swiperSlide.end().find("[data-caption-animate]").addClass("not-animated").end().swiper({autoplay:isNoviBuilder?null:s.attr('data-autoplay')?s.attr('data-autoplay')==="false"?undefined:s.attr('data-autoplay'):5000,direction:s.attr('data-direction')?s.attr('data-direction'):"horizontal",effect:s.attr('data-slide-effect')?s.attr('data-slide-effect'):"slide",speed:s.attr('data-slide-speed')?s.attr('data-slide-speed'):600,keyboardControl:s.attr('data-keyboard')==="true",mousewheelControl:s.attr('data-mousewheel')==="true",mousewheelReleaseOnEdges:s.attr('data-mousewheel-release')==="true",nextButton:next.length?next.get(0):null,prevButton:prev.length?prev.get(0):null,pagination:pag.length?pag.get(0):null,paginationClickable:pag.length?pag.attr("data-clickable")!=="false":false,paginationBulletRender:pag.length?pag.attr("data-index-bullet")==="true"?function(index,className){return '<span class="'+className+'">'+(index+1)+'</span>';}:null:null,scrollbar:bar.length?bar.get(0):null,scrollbarDraggable:bar.length?bar.attr("data-draggable")!=="false":true,scrollbarHide:bar.length?bar.attr("data-draggable")==="false":false,loop:isNoviBuilder?false:s.attr('data-loop')!=="false",simulateTouch:s.attr('data-simulate-touch')&&!isNoviBuilder?s.attr('data-simulate-touch')==="true":false,onTransitionStart:function(swiper){toggleSwiperInnerVideos(swiper);},onTransitionEnd:function(swiper){toggleSwiperCaptionAnimation(swiper);},onInit:function(swiper){toggleSwiperInnerVideos(swiper);toggleSwiperCaptionAnimation(swiper);$(window).on('resize',function(){swiper.update(true);})}});$(window).on("resize",function(){var mh=getSwiperHeight(s,"min-height"),h=getSwiperHeight(s,"height");if(h){s.css("height",mh?mh>h?mh:h:h);}}).trigger("resize");}}
if(plugins.dateCountdown.length){var i;for(i=0;i<plugins.dateCountdown.length;i++){var dateCountdownItem=$(plugins.dateCountdown[i]),time={"Days":{"text":"Days","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"},"Hours":{"text":"Hours","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"},"Minutes":{"text":"Minutes","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"},"Seconds":{"text":"Seconds","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"}};dateCountdownItem.TimeCircles({color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"rgba(247, 247, 247, 1)",animation:"smooth",bg_width:dateCountdownItem.attr("data-bg-width")?dateCountdownItem.attr("data-bg-width"):0.6,circle_bg_color:dateCountdownItem.attr("data-bg")?dateCountdownItem.attr("data-bg"):"rgba(0, 0, 0, 1)",fg_width:dateCountdownItem.attr("data-width")?dateCountdownItem.attr("data-width"):0.03});$(window).on('load resize orientationchange',function(){if(window.innerWidth<479){dateCountdownItem.TimeCircles({time:{"Days":{"text":"Days","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"},"Hours":{"text":"Hours","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"},"Minutes":{"text":"Minutes","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"},Seconds:{"text":"Seconds",show:false,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"}}}).rebuild();}else if(window.innerWidth<767){dateCountdownItem.TimeCircles({time:{"Days":{"text":"Days","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"},"Hours":{"text":"Hours","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"},"Minutes":{"text":"Minutes","show":true,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"},Seconds:{text:'',show:false,color:dateCountdownItem.attr("data-color")?dateCountdownItem.attr("data-color"):"#f9f9f9"}}}).rebuild();}else{dateCountdownItem.TimeCircles({time:time}).rebuild();}});}}
if(plugins.search.length||plugins.searchResults){var handler="bat/rd-search.php";var defaultTemplate='<h6 class="search_title"><a target="_top" href="#{href}" class="search_link">#{title}</a></h6>'+
'<p class="match">#{href}</p>'+
'<p>...#{token}...</p>';var defaultFilter='*.html';if(plugins.search.length){for(i=0;i<plugins.search.length;i++){var searchItem=$(plugins.search[i]),options={element:searchItem,filter:(searchItem.attr('data-search-filter'))?searchItem.attr('data-search-filter'):defaultFilter,template:(searchItem.attr('data-search-template'))?searchItem.attr('data-search-template'):defaultTemplate,live:(searchItem.attr('data-search-live'))?searchItem.attr('data-search-live'):false,liveCount:(searchItem.attr('data-search-live-count'))?parseInt(searchItem.attr('data-search-live')):4,current:0,processed:0,timer:{}};if($('.rd-navbar-search-toggle').length){var toggle=$('.rd-navbar-search-toggle');toggle.on('click',function(){if(!($(this).hasClass('active'))){searchItem.find('input').val('').trigger('propertychange');}});}
if(options.live){var clearHandler=false;searchItem.find('input').on("keyup input propertychange",$.proxy(function(){this.term=this.element.find('input').val().trim();this.spin=this.element.find('.input-group-addon');clearTimeout(this.timer);if(this.term.length>2){this.timer=setTimeout(liveSearch(this),200);if(clearHandler==false){clearHandler=true;$("body").on("click",function(e){if($(e.toElement).parents('.rd-search').length==0){$('#rd-search-results-live').addClass('cleared').html('');}})}}else if(this.term.length==0){$('#'+this.live).addClass('cleared').html('');}},options,this));}
searchItem.submit($.proxy(function(){$('<input />').attr('type','hidden').attr('name',"filter").attr('value',this.filter).appendTo(this.element);return true;},options,this))}}
if(plugins.searchResults.length){var regExp=/\?.*s=([^&]+)\&filter=([^&]+)/g;var match=regExp.exec(location.search);if(match!=null){$.get(handler,{s:decodeURI(match[1]),dataType:"html",filter:match[2],template:defaultTemplate,live:''},function(data){plugins.searchResults.html(data);})}}}
if(plugins.isotope.length){var i,j,isogroup=[];for(i=0;i<plugins.isotope.length;i++){var isotopeItem=plugins.isotope[i],filterItems=$(isotopeItem).closest('.isotope-wrap').find('[data-isotope-filter]'),iso;iso=new Isotope(isotopeItem,{itemSelector:'.isotope-item',layoutMode:isotopeItem.getAttribute('data-isotope-layout')?isotopeItem.getAttribute('data-isotope-layout'):'masonry',filter:'*',masonry:{columnWidth:0.42}});isogroup.push(iso);filterItems.on("click",function(e){e.preventDefault();var filter=$(this),iso=$('.isotope[data-isotope-group="'+this.getAttribute("data-isotope-group")+'"]'),filtersContainer=filter.closest(".isotope-filters");filtersContainer.find('.active').removeClass("active");filter.addClass("active");iso.isotope({itemSelector:'.isotope-item',layoutMode:iso.attr('data-isotope-layout')?iso.attr('data-isotope-layout'):'masonry',filter:this.getAttribute("data-isotope-filter")=='*'?'*':'[data-filter*="'+this.getAttribute("data-isotope-filter")+'"]',masonry:{columnWidth:0.42}});$window.trigger('resize');}).eq(0).trigger("click");}
$(window).on('load',function(){setTimeout(function(){var i;for(i=0;i<isogroup.length;i++){isogroup[i].element.className+=" isotope--loaded";isogroup[i].layout();}},600);setTimeout(function(){$window.trigger('resize');},800);});}
if(isDesktop&&$html.hasClass("wow-animation")&&$(".wow").length){new WOW().init();}
if(plugins.bootstrapTabs.length){for(var i=0;i<plugins.bootstrapTabs.length;i++){var bootstrapTab=$(plugins.bootstrapTabs[i]);if(bootstrapTab.find('.slick-slider').length){bootstrapTab.find('.tabs-custom-list > li > a').on('click',$.proxy(function(){var $this=$(this);var setTimeOutTime=isNoviBuilder?1500:300;setTimeout(function(){$this.find('.tab-content .tab-pane.active .slick-slider').slick('setPosition');},setTimeOutTime);},bootstrapTab));}
var tabs=plugins.bootstrapTabs[i].querySelectorAll('.nav li a');for(var t=0;t<tabs.length;t++){var tab=tabs[t];if(t===0){tab.parentElement.classList.remove('active');$(tab).tab('show');}
tab.addEventListener('click',function(event){event.preventDefault();$(this).tab('show');});}}}
if(plugins.rdInputLabel.length){plugins.rdInputLabel.RDInputLabel();}
if(plugins.regula.length){attachFormValidator(plugins.regula);}
if(plugins.rdMailForm.length){var i,j,k,msg={'MF000':'Successfully sent!','MF001':'Recipients are not set!','MF002':'Form will not work locally!','MF003':'Please, define email field in your form!','MF004':'Please, define type of your form!','MF254':'Something went wrong with PHPMailer!','MF255':'Aw, snap! Something went wrong.'};for(i=0;i<plugins.rdMailForm.length;i++){var $form=$(plugins.rdMailForm[i]);$form.attr('novalidate','novalidate').ajaxForm({data:{"form-type":$form.attr("data-form-type")||"contact","counter":i},beforeSubmit:function(){if(!isNoviBuilder){var form=$(plugins.rdMailForm[this.extraData.counter]);var inputs=form.find("[data-constraints]");if(isValidated(inputs)){var output=$("#"+form.attr("data-form-output"));if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle fa fa-circle-o-notch fa-spin icon-xxs"></span><span>Sending</span></p>');output.addClass("active");}}else{return false;}}},error:function(result){if(!isNoviBuilder){var output=$("#"+$(plugins.rdMailForm[this.extraData.counter]).attr("data-form-output"));output.text(msg[result]);}},success:function(result){if(!isNoviBuilder){var form=$(plugins.rdMailForm[this.extraData.counter]),output=$("#"+form.attr("data-form-output")),$select=form.find('select');if($select.length){for(j=0;j<$select.length;j++){var $selectitem=$($select[j]);$selectitem.select2('val',null);}}
form.addClass('success');result=result.length==5?result:'MF255';output.text(msg[result]);if(result==="MF000"){if(output.hasClass("snackbars")){output.html('<p><span class="icon text-middle fa-check icon-xxs"></span><span>'+msg[result]+'</span></p>');}
output.addClass("success active");}else{if(output.hasClass("snackbars")){output.html(' <p class="snackbars-left"><span class="icon icon-xxs fa-exclamation-triangle text-middle"></span><span>'+msg[result]+'</span></p>');}
output.addClass("error active");}
form.clearForm();form.find('input, textarea').blur();setTimeout(function(){output.removeClass("active error success");form.removeClass('success');},5000);}}});}}
if(plugins.photoSwipeGallery.length){$document.delegate("[data-photo-swipe-item]","click",function(event){event.preventDefault();var $el=$(this),$galleryItems=$el.parents("[data-photo-swipe-gallery]").find("a[data-photo-swipe-item]"),pswpElement=document.querySelectorAll('.pswp')[0],encounteredItems={},pswpItems=[],options,pswpIndex=0,pswp;if($galleryItems.length==0){$galleryItems=$el;}
$galleryItems.each(function(){var $item=$(this),src=$item.attr('href'),size=$item.attr('data-size').split('x'),pswdItem;if($item.is(':visible')){if(!encounteredItems[src]){pswdItem={src:src,w:parseInt(size[0],10),h:parseInt(size[1],10),el:$item};encounteredItems[src]={item:pswdItem,index:pswpIndex};pswpItems.push(pswdItem);pswpIndex++;}}});options={index:encounteredItems[$el.attr('href')].index,getThumbBoundsFn:function(index){var $el=pswpItems[index].el,offset=$el.offset();return{x:offset.left,y:offset.top,w:$el.width()};}};pswp=new PhotoSwipe(pswpElement,PhotoSwipeUI_Default,pswpItems,options);pswp.init();});}
if(plugins.customToggle.length){var i;for(i=0;i<plugins.customToggle.length;i++){var $this=$(plugins.customToggle[i]);$this.on('click',$.proxy(function(event){event.preventDefault();var $ctx=$(this);$($ctx.attr('data-custom-toggle')).add(this).toggleClass('active');},$this));if($this.attr("data-custom-toggle-hide-on-blur")==="true"){$("body").on("click",$this,function(e){if(e.target!==e.data[0]&&$(e.data.attr('data-custom-toggle')).find($(e.target)).length&&e.data.find($(e.target)).length==0){$(e.data.attr('data-custom-toggle')).add(e.data[0]).removeClass('active');}})}
if($this.attr("data-custom-toggle-disable-on-blur")==="true"){$("body").on("click",$this,function(e){if(e.target!==e.data[0]&&$(e.data.attr('data-custom-toggle')).find($(e.target)).length==0&&e.data.find($(e.target)).length==0){$(e.data.attr('data-custom-toggle')).add(e.data[0]).removeClass('active');}})}}}
if(plugins.counter.length){var i;for(i=0;i<plugins.counter.length;i++){var $counterNotAnimated=$(plugins.counter[i]).not('.animated');$document.on("scroll",$.proxy(function(){var $this=this;if((!$this.hasClass("animated"))&&(isScrolledIntoView($this))){$this.countTo({refreshInterval:40,from:0,to:parseInt($this.text(),10),speed:$this.attr("data-speed")||1000,formatter:function(value,options){if($this.attr('data-formatter')!='false'){value=value.toFixed(options.decimals);if(value<10){return '0'+value;}
return value;}else if(value.toString().indexOf('.')!==-1){var decimals=$this.attr('data-to').split('.')[1];return value.toFixed(options.decimals)+'.'+decimals;}else{return value.toFixed(options.decimals);}}});$this.addClass('animated');}},$counterNotAnimated)).trigger("scroll");}}
if(plugins.circleProgress.length){var i;for(i=0;i<plugins.circleProgress.length;i++){var circleProgressItem=$(plugins.circleProgress[i]);$document.on("scroll",function(){if(!circleProgressItem.hasClass('animated')){var arrayGradients=circleProgressItem.attr('data-gradient').split(",");circleProgressItem.circleProgress({value:parseFloat(circleProgressItem.text(),10),size:circleProgressItem.attr('data-size')?circleProgressItem.attr('data-size'):140,fill:{gradient:arrayGradients,gradientAngle:Math.PI/4},startAngle:-Math.PI/4*2,emptyFill:circleProgressItem.attr('data-empty-fill')?circleProgressItem.attr('data-empty-fill'):"rgb(245,245,245)",thickness:circleProgressItem.attr('data-thickness')?parseInt(circleProgressItem.attr('data-thickness')):10,}).on('circle-animation-progress',function(event,progress,stepValue){$(this).find('span').text(String(stepValue.toFixed(2)).replace('0.','').replace('1.','1'));});circleProgressItem.addClass('animated');}}).trigger("scroll");}}
if(plugins.progressLinear.length){for(i=0;i<plugins.progressLinear.length;i++){var progressBar=$(plugins.progressLinear[i]);$window.on("scroll load",$.proxy(function(){var bar=$(this);if(!bar.hasClass('animated-first')&&isScrolledIntoView(bar)){var end=parseInt($(this).find('.progress-value').text(),10);bar.find('.progress-bar-linear').css({width:end+'%'});bar.find('.progress-value').countTo({refreshInterval:40,from:0,to:end,speed:500});bar.addClass('animated-first');}},progressBar));}}
if(plugins.rdParallax.length&&!isMobile){var i;$.RDParallax();if(!isIE&&!isMobile){$(window).on("scroll",function(){for(i=0;i<plugins.rdParallax.length;i++){var parallax=$(plugins.rdParallax[i]);if(isScrolledIntoView(parallax)){parallax.find(".rd-parallax-inner").css("position","fixed");}else{parallax.find(".rd-parallax-inner").css("position","absolute");}}});}
$("a[href='#'], a[href^='#']").on("click",function(event){setTimeout(function(){$(window).trigger("resize");},300);});}
if(plugins.customParallax.length){for(var k=0;k<plugins.customParallax.length;k++){var $this=$(plugins.customParallax[k]),wrapper=$('.custom-parallax-wrap'),parallax=true,speed;if(parallax&&!isIE&&!isMobile){if(speed=$this.attr("data-speed")){makeParallax($this,speed,wrapper,false);}}}}
if(plugins.selectFilter.length){var i;for(i=0;i<plugins.selectFilter.length;i++){var select=$(plugins.selectFilter[i]);select.select2({theme:"bootstrap"}).next().addClass(select.attr("class").match(/(input-sm)|(input-lg)|($)/i).toString().replace(new RegExp(",",'g')," "));}}
if(plugins.flickrfeed.length>0){var i;for(i=0;i<plugins.flickrfeed.length;i++){var flickrfeedItem=$(plugins.flickrfeed[i]);flickrfeedItem.RDFlickr({callback:function(){var items=flickrfeedItem.find("[data-photo-swipe-item]");if(items.length){for(var j=0;j<items.length;j++){var image=new Image();image.setAttribute('data-index',j);image.onload=function(){items[this.getAttribute('data-index')].setAttribute('data-size',this.naturalWidth+'x'+this.naturalHeight);};image.src=items[j].getAttribute('href');}}}});}}
if(plugins.rdVideoBG.length){var i;for(i=0;i<plugins.rdVideoBG.length;i++){var videoItem=$(plugins.rdVideoBG[i]);videoItem.RDVideo({});}}
if(plugins.rdAudioPlayer.length&&!isNoviBuilder){var i;for(i=0;i<plugins.rdAudioPlayer.length;i++){$(plugins.rdAudioPlayer[i]).RDAudio();}}
if(plugins.mfp.length>0||plugins.mfpGallery.length>0&&isNoviBuilder!="designMode"){if(plugins.mfp.length){for(i=0;i<plugins.mfp.length;i++){var mfpItem=plugins.mfp[i];$(mfpItem).magnificPopup({type:mfpItem.getAttribute("data-lightbox")});}}
if(plugins.mfpGallery.length){for(i=0;i<plugins.mfpGallery.length;i++){var mfpGalleryItem=$(plugins.mfpGallery[i]).find('[data-lightbox]');for(var c=0;c<mfpGalleryItem.length;c++){$(mfpGalleryItem).addClass("mfp-"+$(mfpGalleryItem).attr("data-lightbox"));}
mfpGalleryItem.end().magnificPopup({delegate:'[data-lightbox]',type:"image",gallery:{enabled:true}});}}}
function moJsIconsEffect(el,options){this.el=el;this.options=$.extend({},this.options);$.extend(this.options,options);this.checked=false;this.hovered=false;this.timeline=new mojs.Timeline();for(var i=0,len=this.options.tweens.length;i<len;++i){this.timeline.add(this.options.tweens[i]);}
var self=this;this.el.addEventListener('mouseenter',function(e){if(self.hovered==false){self.options.onCheck(self.el);self.timeline.replay();self.hovered=true;self.checked=!self.checked;}});this.el.addEventListener('mouseleave',function(e){if(self.hovered){self.options.onUnCheck(self.el);self.checked=!self.checked;self.hovered=false;}});}
moJsIconsEffect.prototype.options={tweens:[new mojs.Burst({})],onCheck:function(){return false;},onUnCheck:function(){return false;}};if(plugins.mojsIconEffect.length){var iconElements=$('.mojs-icon-effect-5');for(var i=0;i<iconElements.length;i++){var scaleCurve5=mojs.easing.path('M0,100 L25,99.9999983 C26.2328835,75.0708847 19.7847843,0 100,0'),element=iconElements[i],elementSpan;new moJsIconsEffect(element,{tweens:[new mojs.Burst({parent:element,count:15,radius:{20:80},angle:{0:140,easing:mojs.easing.bezier(0.1,1,0.3,1)},children:{fill:'#f47e4b',radius:20,opacity:0.6,duration:1500,easing:mojs.easing.bezier(0.1,1,0.3,1)}}),new mojs.Tween({duration:800,easing:mojs.easing.bezier(0.1,1,0.3,1),onUpdate:$.proxy(function(progress){var scaleProgress=scaleCurve5(progress);elementSpan=this.querySelector('span');elementSpan.style.WebkitTransform=elementSpan.style.transform='scale3d('+progress+','+progress+',1)';},element)})],onCheck:function(ctx){ctx.style.color='#f47e4b';},onUnCheck:function(ctx){ctx.style.color='#efe939';}});}}
if(plugins.mojsIconEffect.length){var iconElements=$('.mojs-icon-effect-6');for(var i=0;i<iconElements.length;i++){var scaleCurve6=mojs.easing.path('M0,100 L25,99.9999983 C26.2328835,75.0708847 19.7847843,0 100,0');element=iconElements[i],elementSpan;new moJsIconsEffect(element,{tweens:[new mojs.Burst({parent:element,radius:{40:110},count:20,children:{shape:'line',fill:'white',radius:{12:0},scale:1,stroke:'#efe939',strokeWidth:2,duration:1500,easing:mojs.easing.bezier(0.1,1,0.3,1)},}),new mojs.Shape({parent:element,radius:{10:60},fill:'transparent',stroke:'#efe939',strokeWidth:{30:0},duration:800,easing:mojs.easing.bezier(0.1,1,0.3,1)}),new mojs.Tween({duration:800,easing:mojs.easing.bezier(0.1,1,0.3,1),onUpdate:$.proxy(function(progress){var scaleProgress=scaleCurve6(progress);elementSpan=this.querySelector('span');elementSpan.style.WebkitTransform=elementSpan.style.transform='scale3d('+progress+','+progress+',1)';},element)})],onCheck:function(ctx){ctx.style.color='#151515';},onUnCheck:function(ctx){ctx.style.color='#151515';}});}}
if(plugins.slick.length){var i;for(i=0;i<plugins.slick.length;i++){var $slickItem=$(plugins.slick[i]);$slickItem.slick({slidesToScroll:parseInt($slickItem.attr('data-slide-to-scroll'))||1,asNavFor:$slickItem.attr('data-for')||false,dots:$slickItem.attr("data-dots")=="true",infinite:$slickItem.attr("data-loop")=="true",focusOnSelect:true,arrows:$slickItem.attr("data-arrows")=="true"||$slickItem.attr('data-custom-arrows')=='true',prevArrow:$slickItem.attr('data-custom-arrows')=='true'?$('.slick-prev[data-slick="'+$slickItem.attr('id')+'"]'):'',nextArrow:$slickItem.attr('data-custom-arrows')=='true'?$('.slick-next[data-slick="'+$slickItem.attr('id')+'"]'):'',swipe:$slickItem.attr("data-swipe")=="true",autoplay:$slickItem.attr("data-autoplay")=="true",vertical:$slickItem.attr("data-vertical")=="true",centerMode:$slickItem.attr("data-center-mode")=="true",centerPadding:$slickItem.attr("data-center-padding")?$slickItem.attr("data-center-padding"):'0.50',mobileFirst:true,responsive:[{breakpoint:0,settings:{slidesToShow:parseInt($slickItem.attr('data-items'))||1,}},{breakpoint:479,settings:{slidesToShow:parseInt($slickItem.attr('data-xs-items'))||1,}},{breakpoint:767,settings:{slidesToShow:parseInt($slickItem.attr('data-sm-items'))||1,}},{breakpoint:991,settings:{slidesToShow:parseInt($slickItem.attr('data-md-items'))||1,}},{breakpoint:1199,settings:{slidesToShow:parseInt($slickItem.attr('data-lg-items'))||1,swipe:false}}]}).on('afterChange',function(event,slick,currentSlide,nextSlide){var $this=$(this),childCarousel=$this.attr('data-child');if(childCarousel){$(childCarousel+' .slick-slide').removeClass('slick-current');$(childCarousel+' .slick-slide').eq(currentSlide).addClass('slick-current');}});}}});